### ISSUE TITLE
load_checkpoint_to_cpu

### ISSUE THREAD

**Issue by igormis** [microsoft/MASS#108]
I am using the summarization code with the pretrained model `MASS-middle-uncased`. However when I execute the script
```
MODEL=./checkpoints/mass-middle-uncased.pt
DATADIR=DATA
fairseq-generate $DATADIR --path $MODEL \
    --user-dir mass --task masked_s2s  \
    --batch-size 64 --beam 5 --min-len 50 --no-repeat-ngram-size 3 \
    --lenpen 1.0 \
    --cpu \
```
I got the following fairseq error:
```
  File "/home/doit/anaconda3/envs/mass-sumarization/lib/python3.6/site-packages/fairseq/checkpoint_utils.py", line 138, in load_checkpoint_to_cpu
    args = state['args']
KeyError: 'args'
```
I believe that it is because I am loading it on CPU, problem with the serialization of the model.

Here is my env:
```
certifi==2019.11.28
cffi==1.13.2
fairseq==0.8.0
fastBPE==0.1.0
numpy==1.17.4
portalocker==1.5.2
pycparser==2.19
regex==2019.11.1
sacrebleu==1.4.3
torch==1.0.0
tqdm==4.40.0
typing==3.7.4.1
```
Any thoughts how to fix this?

Here is the complete output:
```
Namespace(beam=5, bpe=None, cpu=True, criterion='cross_entropy', data='DATA', dataset_impl=None, diverse_beam_groups=-1, diverse_beam_strength=0.5, force_anneal=None, fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, gen_subset='test', lazy_load=False, lenpen=1.0, log_format=None, log_interval=1000, lr_scheduler='fixed', lr_shrink=0.1, mask_s2s_mask_keep_rand='0.8,0.1,0.1', mask_s2s_prob=0.15, match_source_len=False, max_len_a=0, max_len_b=200, max_sentences=64, max_tokens=None, memory_efficient_fp16=False, min_len=50.0, min_loss_scale=0.0001, model_overrides='{}', momentum=0.99, nbest=1, no_beamable_mm=False, no_early_stop=False, no_progress_bar=False, no_repeat_ngram_size=3, num_shards=1, num_workers=1, optimizer='nag', path='checkpoints/mass-middle-uncased.pt', prefix_size=0, print_alignment=False, quiet=False, raw_text=False, remove_bpe=None, replace_unk=None, required_batch_size_multiple=8, results_path=None, sacrebleu=False, sample_break_mode='none', sampling=False, sampling_topk=-1, sampling_topp=-1.0, score_reference=False, seed=1, shard_id=0, skip_invalid_size_inputs_valid_test=False, task='masked_s2s', tbmf_wrapper=False, temperature=1.0, tensorboard_logdir='', threshold_loss_scale=None, tokenizer=None, tokens_per_sample=512, unkpen=0, unnormalized=False, user_dir='mass', warmup_updates=0, weight_decay=0.0)
| dictionary: 30522 types
| loaded 2 examples from: DATA/test
| loading model(s) from checkpoints/mass-middle-uncased.pt
Traceback (most recent call last):
  File "/home/doit/anaconda3/envs/mass-sumarization/bin/fairseq-generate", line 8, in <module>
    sys.exit(cli_main())
  File "/home/doit/anaconda3/envs/mass-sumarization/lib/python3.6/site-packages/fairseq_cli/generate.py", line 186, in cli_main
    main(args)
  File "/home/doit/anaconda3/envs/mass-sumarization/lib/python3.6/site-packages/fairseq_cli/generate.py", line 47, in main
    task=task,
  File "/home/doit/anaconda3/envs/mass-sumarization/lib/python3.6/site-packages/fairseq/checkpoint_utils.py", line 155, in load_model_ensemble
    ensemble, args, _task = load_model_ensemble_and_task(filenames, arg_overrides, task)
  File "/home/doit/anaconda3/envs/mass-sumarization/lib/python3.6/site-packages/fairseq/checkpoint_utils.py", line 166, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/home/doit/anaconda3/envs/mass-sumarization/lib/python3.6/site-packages/fairseq/checkpoint_utils.py", line 138, in load_checkpoint_to_cpu
    args = state['args']
KeyError: 'args'
```

**Comment by StillKeepTry** [comment]
`mass-middle-uncased.pt` is only used for pre-training, since it is not compatible for generation directly (I also do not use the pre-trained model for inference). You can first fine-tune on cnndm or gigaword with `mass-middle-uncased.pt` and then use the fine-tuned model for inference.
