### ISSUE TITLE
Issues with tgt.dict during inference

### ISSUE THREAD

**Issue by RebolloM** [microsoft/MASS#121]
I separated the article (src) and abstract (tgt) into separate files with the according suffixes and tokenized using the instructions from the Readme. Then I ran the fairseq-preprocess and got all of the expected idx and dict files.  However, when I infer I get the below error:

\MASS\MASS-summarization>fairseq-generate Processed --path=checkpoints/cnndm_evaluation/checkpoint.pt --user-dir=mass --task=translation_mass --batch-size=64 --beam=5 --min-len=50 --no-repeat-ngram-size=3 --lenpen=1.0 
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\p3.6\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\envs\p3.6\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\p3.6\Scripts\fairseq-generate.exe\__main__.py", line 7, in <module>
  File "c:\programdata\anaconda3\envs\p3.6\lib\site-packages\fairseq_cli\generate.py", line 199, in cli_main
    main(args)
  File "c:\programdata\anaconda3\envs\p3.6\lib\site-packages\fairseq_cli\generate.py", line 32, in main
    task = tasks.setup_task(args)
  File "c:\programdata\anaconda3\envs\p3.6\lib\site-packages\fairseq\tasks\__init__.py", line 17, in setup_task
    return TASK_REGISTRY[args.task].setup_task(args, **kwargs)
  File "c:\programdata\anaconda3\envs\p3.6\lib\site-packages\fairseq\tasks\translation.py", line 189, in setup_task
    assert src_dict.pad() == tgt_dict.pad()
AssertionError

The dict.tgt file is considerably smaller than the dict.src file and it is missing the [PAD]. What am I doing wrong during the data processing?

Thanks!

**Comment by RebolloM** [comment]
btw, I am using fairseq 0.9.0

**Comment by RebolloM** [comment]
I solved this by adding **--joined-dictionary** to the fairseq-preprocess command.
