### ISSUE TITLE
Unable to load Zh-En Pre-trained Model for fine-tuning

### ISSUE THREAD

**Issue by riddlehk** [microsoft/MASS#153]
Dear authors,

I make use of the [script](https://github.com/microsoft/MASS/blob/master/MASS-supNMT/ft_mass_enzh.sh) to perform fine-tuning on the [zh-en pre-trained model](https://modelrelease.blob.core.windows.net/mass/zhen_mass_pre-training.pt) you provided. After allocating GPUs, dictionaries and binary data, the following error messages popped up:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/opt/conda/lib/python3.6/site-packages/fairseq_cli/train.py", line 265, in distributed_main
    main(args, init_distributed=True)
  File "/opt/conda/lib/python3.6/site-packages/fairseq_cli/train.py", line 68, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(args, trainer)
  File "/opt/conda/lib/python3.6/site-packages/fairseq/checkpoint_utils.py", line 107, in load_checkpoint
    reset_meters=args.reset_meters,
  File "/opt/conda/lib/python3.6/site-packages/fairseq/trainer.py", line 154, in load_checkpoint
    'Cannot load model parameters from checkpoint, '
Exception: Cannot load model parameters from checkpoint, please ensure that the architectures match.
```

I observed that the size of the pre-trained model is much bigger (of size 6425203122) than the checkpoints I obtained by training from scratch (of size ~3220000000), any advice on letting the pre-trained model being successfully loaded?

**Comment by ranggarppb** [comment]
I've got this problem too. Is there any solution for this?
