### ISSUE TITLE
how to decoder with the mass_ft_enfr_1024.pth

### ISSUE THREAD

**Issue by Bournet** [microsoft/MASS#25]
I run the scripts like this,
cat $test | python translate.py --exp_name translate  --src_lang en --tgt_lang fr  --model_path mass_ft_enfr_1024.pth --output_path output

but got the error:

AttributeError: 'AttrDict' object has no attribute 'attention_setting'

**Comment by StillKeepTry** [comment]
@Bournet , Sorry, it has been fixed now for inference. I forget to update the supported parameters in the original model. I will update other uploaded models later. Besides, you can directly load the weight of the fine-tuned model to train on your data.

**Comment by Bournet** [comment]
@StillKeepTry , Thank you for reply. I load the fine-tuned model on my data, and got the model keys error.

Missing key(s) in state_dict: "position_embeddings.weight", ...
Unexpected key(s) in state_dict: "module.position_embeddings.weight", ...

Is there some config wrong?

**Comment by StillKeepTry** [comment]
@Bournet  Maybe use `translate_ensemble.py` to translate? `translate.py` is the original translation script in XLM, and `translate_ensemble.py` is a refined version in our works.

**Comment by esalesky** [comment]
Hello @StillKeepTry I tried translating using the MASS XLM pretrained models, and suspect the other 5 uploaded models have not been updated. 
I can only translate using the fine-tuned en-fr model. 
I tested the other 5 pre-trained and fine-tuned models with both `translate.py` and `translate_ensemble.py` and got one of the two below parameter errors: 

```
INFO - 07/15/19 21:31:59 - 0:00:00 - Running command: python translate_ensemble.py --exp_name pre_enfr_eval --src_lang en --tgt_lang fr --model_path 'mass_enfr_1024.pth' --output_path 'outs/pre_enfr_newstest2014.fr'

Traceback (most recent call last):
  File "translate_ensemble.py", line 322, in <module>
    main(params)
  File "translate_ensemble.py", line 215, in main
    model_params = AttrDict(models_reloaded[0]['params'])
KeyError: 'params'
```

```
INFO - 07/15/19 21:35:39 - 0:00:00 - Running command: python translate_ensemble.py --exp_name pre_deen_eval --src_lang de --tgt_lang en --model_path 'mass_ft_ende_1024.pth' --output_path 'outs/pre_newstest2016-ende.en'

INFO - 07/15/19 21:35:20 - 0:00:16 - Supported languages: de, en
Traceback (most recent call last):
  File "translate_ensemble.py", line 322, in <module>
    main(params)
  File "translate_ensemble.py", line 220, in main
    setattr(params, name, getattr(model_params, name))
AttributeError: 'AttrDict' object has no attribute 'bos_index'
```

**Comment by 520jefferson** [comment]
@StillKeepTry I meet the same problem.
