### ISSUE TITLE
the mass_ende_1024.pth and mass_ft_ende_1024.pth model haven't all the parameters

### ISSUE THREAD

**Issue by 520jefferson** [microsoft/MASS#49]
I meet the same problem. i use translate.py and translate_ensemble.py, the problem is the same. is't ende model is old ? or may i use pretrained-ende model? 
whether  i finetune first , then i can use  the translate.py?

CUDA_VISIBLE_DEVICES=4 cat test |python3 translate.py --exp_name translate --src_lang en --tgt_lang de --model_path ./model_ende/finetune_model/mass_ft_ende_1024.pth --output_path output
INFO - 08/09/19 16:30:19 - 0:00:00 - ============ Initialized logger ============
INFO - 08/09/19 16:30:19 - 0:00:00 - batch_size: 32
beam: 1
command: python translate.py --exp_name translate --src_lang en --tgt_lang de --model_path './model_ende/finetune_model/mass_ft_ende_1024.pth' --output_path output --exp_id "875c0m2q9t"
dump_path: ./dumped/translate/875c0m2q9t
exp_id: 875c0m2q9t
exp_name: translate
fp16: False
length_penalty: 1
model_path: ./model_ende/finetune_model/mass_ft_ende_1024.pth
output_path: output
src_lang: en
tgt_lang: de
INFO - 08/09/19 16:30:19 - 0:00:00 - The experiment will be stored in ./dumped/translate/875c0m2q9t

INFO - 08/09/19 16:30:19 - 0:00:00 - Running command: python translate.py --exp_name translate --src_lang en --tgt_lang de --model_path './model_ende/finetune_model/mass_ft_ende_1024.pth' --output_path output

INFO - 08/09/19 16:30:26 - 0:00:07 - Supported languages: en, de
Traceback (most recent call last):
File "translate.py", line 160, in 
main(params)
File "translate.py", line 77, in main
setattr(params, name, getattr(model_params, name))
AttributeError: 'AttrDict' object has no attribute 'bos_index'

**Comment by PlayDeep** [comment]
you can see a eport all the params during training with MASS code. and will be ok.

**Comment by StillKeepTry** [comment]
Can you try again with the latest model?

**Comment by bcmi220** [comment]
same problem

**Comment by 520jefferson** [comment]
same proble, even using the new model and newly updated codes, weird!

**Comment by gloriacodes** [comment]
confirming same problem using only the provided finetuned model, it works perfectly on french translation only. 
input file is not bpe-ized (using txt test references) that may be the source of the problem

**Comment by TinyFlames** [comment]
same problem!
