### ISSUE TITLE
Not all gradients have been reduced from the backward of the previous iteration

### ISSUE THREAD

**Issue by huangxianliang** [microsoft/MASS#76]
i try to pre-train supNMT,but this error occur:Not all gradients have been reduced from the backward of the previous iteration.
why so many errors occur in my training process, i am crying......

**Comment by huangxianliang** [comment]
this is the detail of gradients error:
-- Process 1 terminated with the following error:
Traceback (most recent call last):
File "/home/slurm/job/tmp/job-139545/env/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
fn(i, *args)
File "/home/slurm/job/tmp/job-139545/env/lib/python3.6/site-packages/fairseq-0.7.1-py3.6-linux-x86_64.egg/fairseq_cli/train.py", line 265, in distributed_main
main(args, init_distributed=True)
File "/home/slurm/job/tmp/job-139545/env/lib/python3.6/site-packages/fairseq-0.7.1-py3.6-linux-x86_64.egg/fairseq_cli/train.py", line 80, in main
train(args, trainer, task, epoch_itr)
File "/home/slurm/job/tmp/job-139545/env/lib/python3.6/site-packages/fairseq-0.7.1-py3.6-linux-x86_64.egg/fairseq_cli/train.py", line 121, in train
log_output = trainer.train_step(samples)
File "/home/slurm/job/tmp/job-139545/env/lib/python3.6/site-packages/fairseq-0.7.1-py3.6-linux-x86_64.egg/fairseq/trainer.py", line 283, in train_step
raise e
File "/home/slurm/job/tmp/job-139545/env/lib/python3.6/site-packages/fairseq-0.7.1-py3.6-linux-x86_64.egg/fairseq/trainer.py", line 260, in train_step
ignore_grad
File "/home/slurm/job/tmp/job-139545/mass/xmasked_seq2seq.py", line 398, in train_step
forward_backward(model, sample[sample_key], sample_key, lang_pair)
File "/home/slurm/job/tmp/job-139545/mass/xmasked_seq2seq.py", line 383, in forward_backward
loss, sample_size, logging_output = criterion(model, samples)
File "/home/slurm/job/tmp/job-139545/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in call
result = self.forward(*input, **kwargs)
File "/home/slurm/job/tmp/job-139545/env/lib/python3.6/site-packages/fairseq-0.7.1-py3.6-linux-x86_64.egg/fairseq/criterions/label_smoothed_cross_entropy.py", line 38, in forward
net_output = model(**sample['net_input'])
File "/home/slurm/job/tmp/job-139545/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in call
result = self.forward(*input, **kwargs)
File "/home/slurm/job/tmp/job-139545/env/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 353, in forward
self._check_previous_reduction()
File "/home/slurm/job/tmp/job-139545/env/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 343, in _check_previous_reduction
raise RuntimeError("Not all gradients have been reduced from "
RuntimeError: Not all gradients have been reduced from the backward of the previous iteration. This is unexpected and fatal error. Please check and ensure that the model's parameters are not changed after you wrap up the model with DistributedDataParallel.
