### ISSUE TITLE
Talk about my feelings while pretraining supNMT

### ISSUE THREAD

**Issue by huangxianliang** [microsoft/MASS#77]
First of all, let me introduce my needs.i have a large of supervised pair of tilte-query just like data from search engines, titles and querys are all Chinese,i want to generate new query with new title by using supNMT.

Firstly,i try to pretrain with the guide https://github.com/microsoft/MASS/blob/master/MASS-supNMT/README.md. In this part,i just change en and zh to src and tgt.But error occur:RuntimeError: Not all gradients have been reduced from the backward of the previous iteration. This is unexpected and fatal error. Please check and ensure that the model's parameters are not changed after you wrap up the model with DistributedDataParallel. 

Then,i am thinking...... Are my parameters incorrect? But i was followed the README.md. Is my data format incorrect? 

Secondly,i megered querys and titles to one language alias ch,but it didn't work.

I am very confused all along the line, i don't really know the meaning of some parameters, --mass_steps --memt_steps --mt_steps.I am very confused. There is no much detailed description in the README

**Comment by huangxianliang** [comment]
this is the detail of gradients error:
-- Process 1 terminated with the following error:
Traceback (most recent call last):
File "/home/slurm/job/tmp/job-139545/env/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
fn(i, *args)
File "/home/slurm/job/tmp/job-139545/env/lib/python3.6/site-packages/fairseq-0.7.1-py3.6-linux-x86_64.egg/fairseq_cli/train.py", line 265, in distributed_main
main(args, init_distributed=True)
File "/home/slurm/job/tmp/job-139545/env/lib/python3.6/site-packages/fairseq-0.7.1-py3.6-linux-x86_64.egg/fairseq_cli/train.py", line 80, in main
train(args, trainer, task, epoch_itr)
File "/home/slurm/job/tmp/job-139545/env/lib/python3.6/site-packages/fairseq-0.7.1-py3.6-linux-x86_64.egg/fairseq_cli/train.py", line 121, in train
log_output = trainer.train_step(samples)
File "/home/slurm/job/tmp/job-139545/env/lib/python3.6/site-packages/fairseq-0.7.1-py3.6-linux-x86_64.egg/fairseq/trainer.py", line 283, in train_step
raise e
File "/home/slurm/job/tmp/job-139545/env/lib/python3.6/site-packages/fairseq-0.7.1-py3.6-linux-x86_64.egg/fairseq/trainer.py", line 260, in train_step
ignore_grad
File "/home/slurm/job/tmp/job-139545/mass/xmasked_seq2seq.py", line 398, in train_step
forward_backward(model, sample[sample_key], sample_key, lang_pair)
File "/home/slurm/job/tmp/job-139545/mass/xmasked_seq2seq.py", line 383, in forward_backward
loss, sample_size, logging_output = criterion(model, samples)
File "/home/slurm/job/tmp/job-139545/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
result = self.forward(*input, **kwargs)
File "/home/slurm/job/tmp/job-139545/env/lib/python3.6/site-packages/fairseq-0.7.1-py3.6-linux-x86_64.egg/fairseq/criterions/label_smoothed_cross_entropy.py", line 38, in forward
net_output = model(**sample['net_input'])
File "/home/slurm/job/tmp/job-139545/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
result = self.forward(*input, **kwargs)
File "/home/slurm/job/tmp/job-139545/env/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 353, in forward
self._check_previous_reduction()
File "/home/slurm/job/tmp/job-139545/env/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 343, in _check_previous_reduction
raise RuntimeError("Not all gradients have been reduced from "
RuntimeError: Not all gradients have been reduced from the backward of the previous iteration. This is unexpected and fatal error. Please check and ensure that the model's parameters are not changed after you wrap up the model with DistributedDataParallel.

**Comment by robotsp** [comment]
Do you resolve the problem?

**Comment by StillKeepTry** [comment]
> First of all, let me introduce my needs.i have a large of supervised pair of tilte-query just like data from search engines, titles and querys are all Chinese,i want to generate new query with new title by using supNMT.
> 
> Firstly,i try to pretrain with the guide https://github.com/microsoft/MASS/blob/master/MASS-supNMT/README.md. In this part,i just change en and zh to src and tgt.But error occur:RuntimeError: Not all gradients have been reduced from the backward of the previous iteration. This is unexpected and fatal error. Please check and ensure that the model's parameters are not changed after you wrap up the model with DistributedDataParallel.
> 
> Then,i am thinking...... Are my parameters incorrect? But i was followed the README.md. Is my data format incorrect?
> 
> Secondly,i megered querys and titles to one language alias ch, and remove param --memt_steps,it worked. However, i don't know whether is right.
> 
> I am very confused all along the line, i don't really know the meaning of some parameters, --mass_steps --memt_steps --mt_steps.I am very confused. There is no much detailed description in the README

mt_steps is equal to standard supervised training, while memt_steps is similar to mt_steps but allow some noise in the input. You can remove memt_steps or replace memt_steps with mt_steps.

Besides, can you share the  format of your generated data. Besides, do you add --ddp-backend=no_c10d when using DistributedDataParallel
