### ISSUE TITLE
MASS-Summarization get error in Inference

### ISSUE THREAD

**Issue by jimmyhsia** [microsoft/MASS#79]
When i use the script to implement Inference and get error like 
`Traceback (most recent call last):
  File "/home/user/.local/bin/fairseq-generate", line 11, in <module>
    load_entry_point('fairseq==0.8.0', 'console_scripts', 'fairseq-generate')()
  File "/home/user/.local/lib/python3.7/site-packages/fairseq_cli/generate.py", line 186, in cli_main
    main(args)
  File "/home/user/.local/lib/python3.7/site-packages/fairseq_cli/generate.py", line 32, in main
    task = tasks.setup_task(args)
  File "/home/user/.local/lib/python3.7/site-packages/fairseq/tasks/__init__.py", line 17, in setup_task
    return TASK_REGISTRY[args.task].setup_task(args, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/fairseq/tasks/translation.py", line 155, in setup_task
    raise Exception('Could not infer language pair, please provide it explicitly')
Exception: Could not infer language pair, please provide it explicitly`
what i miss?? or it need input language type
anyone help ,thank

**Comment by StillKeepTry** [comment]
Can you give more details about your running scripts? @jimmyhsia

**Comment by steremma** [comment]
I have the same issue. I have downloaded the binarised data files (called `finished_files.zip` from [here](https://github.com/JafferWilson/Process-Data-of-CNN-DailyMail) into `cnndm/processed` and the FT model base. I also cloned MASS. I am launching inference as:

```
DATADIR=cnndm/processed/
MODEL=mass-base-uncased.pt
fairseq-generate $DATADIR --path $MODEL --user-dir MASS/MASS-summarization/mass/ --task translation_mass  --batch-size 64 --beam 5 --min-len 50 --no-repeat-ngram-size 3 --lenpen 1.0 
```

I get the same error reported above:
```
$ fairseq-generate $DATADIR --path $MODEL     --user-dir MASS/MASS-summarization/mass/ --task translation_mass     --batch-size 64 --beam 5 --min-len 50 --no-repeat-ngram-size 3     --lenpen 1.0 
Namespace(beam=5, bpe=None, cpu=False, criterion='cross_entropy', data='cnndm/processed/', dataset_impl=None, diverse_beam_groups=-1, diverse_beam_strength=0.5, force_anneal=None, fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, gen_subset='test', lazy_load=False, left_pad_source='True', left_pad_target='False', lenpen=1.0, log_format=None, log_interval=1000, lr_scheduler='fixed', lr_shrink=0.1, match_source_len=False, max_len_a=0, max_len_b=200, max_sentences=64, max_source_positions=1024, max_target_positions=1024, max_tokens=None, memory_efficient_fp16=False, min_len=50.0, min_loss_scale=0.0001, model_overrides='{}', momentum=0.99, nbest=1, no_beamable_mm=False, no_early_stop=False, no_progress_bar=False, no_repeat_ngram_size=3, num_shards=1, num_workers=1, optimizer='nag', path='mass-base-uncased.pt', prefix_size=0, print_alignment=False, quiet=False, raw_text=False, remove_bpe=None, replace_unk=None, required_batch_size_multiple=8, results_path=None, sacrebleu=False, sampling=False, sampling_topk=-1, sampling_topp=-1.0, score_reference=False, seed=1, shard_id=0, skip_invalid_size_inputs_valid_test=False, source_lang=None, target_lang=None, task='translation_mass', tbmf_wrapper=False, temperature=1.0, tensorboard_logdir='', threshold_loss_scale=None, tokenizer=None, unkpen=0, unnormalized=False, upsample_primary=1, user_dir='MASS/MASS-summarization/mass/', warmup_updates=0, weight_decay=0.0)
Traceback (most recent call last):
  File "/mnt/work/home/estergiadis/mass_env/bin/fairseq-generate", line 8, in <module>
    sys.exit(cli_main())
  File "/mnt/work/home/estergiadis/mass_env/lib/python3.6/site-packages/fairseq_cli/generate.py", line 186, in cli_main
    main(args)
  File "/mnt/work/home/estergiadis/mass_env/lib/python3.6/site-packages/fairseq_cli/generate.py", line 32, in main
    task = tasks.setup_task(args)
  File "/mnt/work/home/estergiadis/mass_env/lib/python3.6/site-packages/fairseq/tasks/__init__.py", line 17, in setup_task
    return TASK_REGISTRY[args.task].setup_task(args, **kwargs)
  File "/mnt/work/home/estergiadis/mass_env/lib/python3.6/site-packages/fairseq/tasks/translation.py", line 155, in setup_task
    raise Exception('Could not infer language pair, please provide it explicitly')
Exception: Could not infer language pair, please provide it explicitly
```

I then tried to pass language as english for both source and target, and renamed `dict.txt` to `cnndm/processed/dict.en.txt` to get rid of `FileNotFoundError`. Now I get this:

```
$ fairseq-generate $DATADIR --path $MODEL     --user-dir MASS/MASS-summarization/mass/ --task translation_mass     --batch-size 64 --beam 5 --min-len 50 --no-repeat-ngram-size 3     --lenpen 1.0 --source-lang en --target-lang en
Namespace(beam=5, bpe=None, cpu=False, criterion='cross_entropy', data='cnndm/processed/', dataset_impl=None, diverse_beam_groups=-1, diverse_beam_strength=0.5, force_anneal=None, fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, gen_subset='test', lazy_load=False, left_pad_source='True', left_pad_target='False', lenpen=1.0, log_format=None, log_interval=1000, lr_scheduler='fixed', lr_shrink=0.1, match_source_len=False, max_len_a=0, max_len_b=200, max_sentences=64, max_source_positions=1024, max_target_positions=1024, max_tokens=None, memory_efficient_fp16=False, min_len=50.0, min_loss_scale=0.0001, model_overrides='{}', momentum=0.99, nbest=1, no_beamable_mm=False, no_early_stop=False, no_progress_bar=False, no_repeat_ngram_size=3, num_shards=1, num_workers=1, optimizer='nag', path='mass-base-uncased.pt', prefix_size=0, print_alignment=False, quiet=False, raw_text=False, remove_bpe=None, replace_unk=None, required_batch_size_multiple=8, results_path=None, sacrebleu=False, sampling=False, sampling_topk=-1, sampling_topp=-1.0, score_reference=False, seed=1, shard_id=0, skip_invalid_size_inputs_valid_test=False, source_lang='en', target_lang='en', task='translation_mass', tbmf_wrapper=False, temperature=1.0, tensorboard_logdir='', threshold_loss_scale=None, tokenizer=None, unkpen=0, unnormalized=False, upsample_primary=1, user_dir='MASS/MASS-summarization/mass/', warmup_updates=0, weight_decay=0.0)
| [en] dictionary: 30522 types
| [en] dictionary: 30522 types
Traceback (most recent call last):
  File "/mnt/work/home/estergiadis/mass_env/bin/fairseq-generate", line 8, in <module>
    sys.exit(cli_main())
  File "/mnt/work/home/estergiadis/mass_env/lib/python3.6/site-packages/fairseq_cli/generate.py", line 186, in cli_main
    main(args)
  File "/mnt/work/home/estergiadis/mass_env/lib/python3.6/site-packages/fairseq_cli/generate.py", line 33, in main
    task.load_dataset(args.gen_subset)
  File "/mnt/work/home/estergiadis/mass_env/lib/python3.6/site-packages/fairseq/tasks/translation.py", line 188, in load_dataset
    max_target_positions=self.args.max_target_positions,
  File "/mnt/work/home/estergiadis/mass_env/lib/python3.6/site-packages/fairseq/tasks/translation.py", line 46, in load_langpair_dataset
    raise FileNotFoundError('Dataset not found: {} ({})'.format(split, data_path))
FileNotFoundError: Dataset not found: test (cnndm/processed/)
```

even though the file is there:

```
$ ls cnndm/processed/
dict.en.txt  test.bin  train.bin  val.bin  vocab
```

Any idea what I am doing wrong?

**Comment by A-Rain** [comment]
@jimmyhsia have solve it? I have met the same problem.
