### ISSUE TITLE
summarization binarization part error

### ISSUE THREAD

**Issue by rabeehk** [microsoft/MASS#80]
Hi,
when I run the binarization part of summarization, I got the following error, thanks a lot for your help.

Namespace(alignfile=None, bpe=None, cpu=False, criterion='cross_entropy', dataset_impl='mmap', destdir='processed', fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, joined_dictionary=False, log_format=None, log_interval=1000, lr_scheduler='fixed', memory_efficient_fp16=False, min_loss_scale=0.0001, no_progress_bar=False, nwordssrc=-1, nwordstgt=-1, only_source=True, optimizer='nag', padding_factor=8, seed=1, source_lang=None, srcdict='dict.txt', target_lang=None, task='translation', tbmf_wrapper=False, tensorboard_logdir='', testpref='mono/test.txt', tgtdict=None, threshold_loss_scale=None, thresholdsrc=0, thresholdtgt=0, tokenizer=None, trainpref='mono/train.txt', user_dir='mass', validpref='mono/valid.txt', workers=60)
| [None] Dictionary: 30525 types
Traceback (most recent call last):
  File "/idiap/user/rkarimi/libs/anaconda3/envs/transformer36/bin/fairseq-preprocess", line 10, in <module>
    sys.exit(cli_main())
  File "/idiap/user/rkarimi/libs/anaconda3/envs/transformer36/lib/python3.6/site-packages/fairseq_cli/preprocess.py", line 265, in cli_main
    main(args)
  File "/idiap/user/rkarimi/libs/anaconda3/envs/transformer36/lib/python3.6/site-packages/fairseq_cli/preprocess.py", line 183, in main
    make_all(args.source_lang, src_dict)
  File "/idiap/user/rkarimi/libs/anaconda3/envs/transformer36/lib/python3.6/site-packages/fairseq_cli/preprocess.py", line 173, in make_all
    make_dataset(vocab, args.trainpref, "train", lang, num_workers=args.workers)
  File "/idiap/user/rkarimi/libs/anaconda3/envs/transformer36/lib/python3.6/site-packages/fairseq_cli/preprocess.py", line 169, in make_dataset
    make_binary_dataset(vocab, input_prefix, output_prefix, lang, num_workers)
  File "/idiap/user/rkarimi/libs/anaconda3/envs/transformer36/lib/python3.6/site-packages/fairseq_cli/preprocess.py", line 155, in make_binary_dataset
    100 * sum(replaced.values()) / n_seq_tok[1],
ZeroDivisionError: division by zero

**Comment by StillKeepTry** [comment]
@rabeehk can you show me your running script ?
